USE REVSTUDB;
SELECT * FROM student

BEGIN TRANSACTION ;

INSERT INTO STUDENT VALUES (101,'AAA','QWERY','AP',523166);
INSERT INTO STUDENT VALUES (102,'BBB','CHENNAI','CH',52318);
-- SAVE POINT --
SAVE TRANSACTION LEVEL1;

-- COOMMIT --
COMMIT TRANSACTION

INSERT INTO STUDENT (ROLLNO,SNAME,PIN)
VALUES(103,'RAM',378478472);

 SAVE TRANSACTION LEVEL2;

UPDATE STUDENT SET ADDR ='AP'
WHERE ROLLNO=103;

ROLLBACK TRANSACTION LEVEL2;

UPDATE STUDENT SET CITY ='CHN'
WHERE ROLLNO=102;

UPDATE STUDENT SET CITY ='BLR'
WHERE ROLLNO=101;

DELETE FROM STUDENT WHERE ROLLNO=103;

TRUNCATE TABLE STUDENT;

SELECT * FROM STUDENT;

-- DQL --

CREATE DATABASE REVCOMPANYDB;
USE REVCOMPANYDB;
CREATE TABLE DEPT(DEPTNO SMALLINT,DNAME VARCHAR(3) NOT NULL,
CONSTRAINT PK_DEPTNO PRIMARY KEY(DEPTNO));

CREATE TABLE EMP(EMPNO SMALLINT,
ENAME VARCHAR(30) NOT NULL,
MGR SMALLINT,
SAL NUMERIC(10,2),
COMM NUMERIC(7,2),
DEPTNO SMALLINT,
CONSTRAINT PK_EMNO PRIMARY KEY(EMPNO),
CONSTRAINT FK_DEPNO FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));

INSERT INTO DEPT VALUES (10,'IT')
INSERT INTO DEPT VALUES (20,'HR')
INSERT INTO DEPT VALUES (30,'SAL')
INSERT INTO DEPT VALUES (40,'MKT')
INSERT INTO DEPT VALUES (50,'OPS')

SELECT * FROM DEPT

INSERT INTO emp (empno, ename, mgr, sal, comm, deptno) VALUES
(1001, 'Alice', NULL, 60000.00, NULL, 10),
(1002, 'Bob', 1001, 75000.00, NULL, 20),   
(1003, 'Charlie', 1002, 50000.00, 500.00, 30), 
(1004, 'Diana', 1003, 52000.00, 300.00, 30),   
(1005, 'Ethan', 1002, 58000.00, NULL, 40), 
(1006, 'Fiona', 1005, 62000.00, NULL, 50);  
SELECT * FROM EMP
-- COLUMN ABSTRACTION
SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP;
-- ROWS 
SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE SAL>60000;

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE EMPNO!=1004;

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE EMPNO IN (1002,1003,1005);

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' , SAL FROM EMP
WHERE SAL BETWEEN 40000 AND 55000;

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE ENAME = 'BOB';

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE ENAME LIKE '%E%';
SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE ENAME LIKE 'D_A%';

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE ENAME NOT IN ('ALICE','FIONA');

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE ENAME  IN ('ALICE','FIONA');

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME' FROM EMP
WHERE EMPNO=1004 OR ENAME LIKE '%A%';

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME',SAL AS 'SALARY' FROM EMP
WHERE SAL>50000
-- ORDER BY
SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME',SAL AS 'SALARY' FROM EMP
WHERE SAL>50000
ORDER BY SAL DESC;

SELECT EMPNO AS 'EMP NUM' ,ENAME AS 'NAME',SAL AS 'SALARY',COMM AS 'COMMISSION'FROM EMP
WHERE SAL>50000
ORDER BY SAL DESC,COMM ASC;

SELECT COUNT(EMPNO) AS 'NO OF EMP '
FROM EMP
WHERE SAL>50000

SELECT COUNT(EMPNO) AS 'NO OF EMP ',SUM(SAL) AS 'TOTAL SALARY',
AVG(COMM) AS 'AVG COMM',MIN(SAL) AS 'MINIMUM SALARY',
MAX(SAL) AS 'MAXIMUM SALARY'
FROM EMP
WHERE SAL>50000

SELECT * FROM EMP
SELECT DEPTNO AS 'DEPARTMENT',SUM(SAL) AS 'TOTAL SALARY'
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO AS 'DEPARTMENT',SUM(SAL) AS 'TOTAL SALARY'
FROM EMP
GROUP BY DEPTNO
HAVING DEPTNO IN (10,30,50)

SELECT DEPTNO AS 'DEPARTMENT',SUM(SAL) AS 'TOTAL SALARY'
FROM EMP

GROUP BY DEPTNO
HAVING DEPTNO IN (10,30,50)

SELECT DEPTNO AS 'DEPARTMENT',SUM(SAL) AS 'TOTAL SALARY'
FROM EMP
WHERE DEPTNO IN (10,30,50)
GROUP BY DEPTNO 
HAVING SUM(SAL) >= 62000
ORDER BY SUM(SAL)

-- JOINS --
INSERT INTO DEPT VALUES (60,'QC')
INSERT INTO DEPT VALUES (70,'CC')

INSERT INTO emp (empno, ename, mgr, sal, comm, deptno) VALUES
(1007, 'AAA', 1002, 60000.00, NULL, NULL), 
(1008, 'BB', 1001, 75000.00, NULL, NULL),   
(1009, 'C', 1002, 50000.00, 500.00, NULL);

SELECT E.ENAME,D.DNAME
FROM EMP E INNER JOIN DEPT D
ON D.DEPTNO = E.DEPTNO;


SELECT E.ENAME,D.DNAME
FROM EMP E LEFT OUTER JOIN DEPT D
ON D.DEPTNO = E.DEPTNO;

SELECT E.ENAME,D.DNAME
FROM EMP E RIGHT OUTER JOIN DEPT D
ON D.DEPTNO = E.DEPTNO;

SELECT E.ENAME,D.DNAME
FROM EMP E FULL OUTER JOIN DEPT D
ON D.DEPTNO = E.DEPTNO;