 USE REVCOMPANYDB

SELECT E.ENAME AS 'EMPLOYEE',M.ENAME AS 'MANAGER' 
FROM EMP E JOIN EMP M
ON E.MGR = M.EMPNO

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT E.ENAME AS 'EMPLOYEE',D.DEPTNO AS 'DEPTNO' 
FROM EMP E CROSS JOIN dept d

SELECT * 
FROM EMP E CROSS JOIN dept d

-- SUBQUERY
--INLINE QUERY

SELECT ENAME
FROM EMP
WHERE DEPTNO =
(SELECT DEPTNO
FROM DEPT
WHERE DNAME='SAL')


SELECT ENAME
FROM EMP
WHERE DEPTNO =
(SELECT DEPTNO
FROM DEPT
WHERE DNAME='IT')

SELECT ENAME,SAL FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP)

-- VIEW
SELECT * FROM  EMP;

CREATE VIEW VEMP AS SELECT EMPNO,ENAME FROM EMP WHERE DEPTNO IN (10,20,30);

SELECT * FROM VEMP

INSERT INTO EMP(EMPNO,ENAME,DEPTNO) VALUES (1110,'XXX',20)
INSERT INTO VEMP VALUES (1111,'YYYY')
UPDATE VEMP SET EMPNO = 10000 WHERE EMPNO = 1111
DELETE FROM VEMP WHERE EMPNO = 1111
DROP VIEW VEMP

-- INDEX
CREATE NONCLUSTERED INDEX IDEPTNO ON EMP(DEPTNO)
DROP INDEX EMP.IDEPTNO

CREATE OR ALTER PROCEDURE SP_EMPDATA
@EMPNO INT,@ENAME VARCHAR,@DEPTNO INT
AS 
BEGIN
BEGIN TRANSACTION
INSERT INTO EMP(EMPNO,ENAME,DEPTNO) VALUES (@EMPNO,@ENAME,@DEPTNO)
COMMIT
SELECT * FROM EMP
END